### ISSUE TITLE
Demo with motion constraints?

### ISSUE THREAD

**Issue by JiatianWu** [gtrll/gpmp2#16]
Hi guys,
    Thank you for your amazing work! Is it possible to make some demos with constraints on trajectory state? For example, moving a glass of water from A to B with keeping glass balanced? If not, would you please give some hints? That will be very helpful. Thank you so much.

Best,
Jiatian

**Comment by mhmukadam** [comment]
Hi Jaitian,

Thank you for your interest in our work. The motion constraints are recently in development in the branch feature/workspaceConstraints. I will adding some Matlab examples very soon. Once the branch is merged in to master, these features should be ready to use.

Best,
Mustafa

**Comment by JiatianWu** [comment]
Thank you! Looking forward to it. Also, I am very interested to contribute to GPMP, is there a to do list that is open for contribution?

**Comment by mhmukadam** [comment]
That's great! We have just added a note about it in [CONTRIBUTING.md](https://github.com/gtrll/gpmp2/blob/master/CONTRIBUTING.md). Please email us if you are interested in anything from the TODO list or if you have anything else in mind and we can discuss more.
