### ISSUE TITLE
Undefined error 

### ISSUE THREAD

**Issue by JiatianWu** [gtrll/gpmp2#21]
I followed the instruction of make matlab wrapper, and there is gpmp2_wrapper.mexa64 under the folder of GTSAM toolbox, and I already add the toolbox path into matlab. However I still got  undefined error like this:

>> Arm2FactorGraphExample
Undefined function or variable 'PlanarSDF'.

Error in Arm2FactorGraphExample (line 21)
sdf = PlanarSDF(origin_point2, cell_size, field);

could you please help me figure out why this happens?

**Comment by dongjing3309** [comment]
Hi, looks like either GTSAM or GPMP2 matlab toolbox is not correctly installed. Have you tried to run any GTSAM exmaple with the same setting?

**Comment by JiatianWu** [comment]
Thanks Jing, I successfully installed GTSAM toolbox, but here is some problem I met running same code:
`Undefined function or variable 'Arm'.

Error in gpmp2.generateArm (line 25)
    arm = Arm(2, a, alpha, d);

Error in Arm2FactorGraphExample (line 40)
arm = generateArm('SimpleTwoLinksArm');`

do you know how to solve it? Thank you very much.

**Comment by JiatianWu** [comment]
Thank you Jing, I successfully installed GTSAM and GPMP2 matlab toolbox, but when I run Arm2FactorGraphExample.m, I got some error like below:

`Error using gtsam.Values/insert (line 117)
Arguments do not match any overload of function gtsam.Values.insert

Error in Arm3FactorGraphExample (line 84)
    init_values.insert(key_pos, pose);`

do you know how to solve it? Thank you very much.

**Comment by JiatianWu** [comment]
I used the precompiled GTSAM toolbox, which is gtsam-toolbox-3.2.0-lin64.tgz. I think it is not latest. Could you please share the latest GTSAM toolbox with me? I have been struggling with compiling it from source code for a long time..My email address is [jiatian1@andrew.cmu.edu](jiatian1@andrew.cmu.edu) That would be really helpful.

**Comment by JiatianWu** [comment]
Also, my platform is Ubuntu 16.04, is it a trusted system?

**Comment by dongjing3309** [comment]
Hi @JiatianWu , GPMP2 needs current version of GTSAM 4, not GTSAM 3.x. So you need to checkout GTSAM repo at https://bitbucket.org/gtborg/gtsam/src, and compile the toolbox as instructed on bitbucket. I don't think GTSAM4 has pre-compiled toolbox available. Ubuntu 16.04 is definitely fine.

**Comment by JiatianWu** [comment]
Thank you Dong, I have successfully run these Matlab demos. Amazing work, I really like your idea that doing motion planning from probabilistic inference. I am currently developing GPMP2 to add motion constraints, hope we can keep in touch in the future. Do you mind if I can add your wechat? My wechat account is WujiatianPumpkin, thank you.
