### ISSUE TITLE
plotSignedDistanceField3D.m

### ISSUE THREAD

**Issue by Huan2018** [gtrll/gpmp2#23]
why use "h = plot3(grid_X(y), grid_Y(x), grid_Z(z), ", not "h = plot3(grid_X(x), grid_Y(y), grid_Z(z),"
![image](https://user-images.githubusercontent.com/40014373/41483408-5f137802-711c-11e8-8460-a0b8b63b617f.png)

**Comment by mhmukadam** [comment]
Yes, that's pretty much what's going on.

**Comment by Huan2018** [comment]
thanks for your help
