### ISSUE TITLE
pos and vel flag limits

### ISSUE THREAD

**Issue by mfinean** [gtrll/gpmp2#24]
https://github.com/gtrll/gpmp2/blob/0e9d9f9e1ef232654493774197c007998f7b8cfb/matlab/Arm3PlannerExample.m#L120

I had an error on running this example. 
I think that there are two separate flags that need to be set:
opt_setting.set_flag_pos_limit and opt_setting.set_flag_vel_limit

**Comment by mhmukadam** [comment]
Thank you for pointing out the bug, it has been fixed.
