### ISSUE TITLE
C++ Example code

### ISSUE THREAD

**Issue by hclin77923** [gtrll/gpmp2#25]
Hello Jing Dong and Mustafa Mukadam,

This is very interesting motion planning framework. Thank you for sharing the source code and well-documented instruction. 
Is it possible to share an example code how you use this planner in C++? For instance, how did you use GPMP2 in OpenRAVE (and benchmarking with trajOpt, CHOMP, OMPL, etc)? I believe that will be very helpful for people want to use this planner.  
Really appreciate it! Thank you! 

Best Regards,
John

**Comment by mhmukadam** [comment]
Hi John, thank you for your interest!

We have a old plugin for OpenRAVE, [orgpmp2](https://github.com/gtrll/orgpmp2). It is deprecated however and will not work with the new features in GPMP2, but you can still run the plugin with the [initial release](https://github.com/gtrll/gpmp2/tree/0.1.0) of GPMP2.

If you want to look at how to use GPMP2 in C++ you can also refer to the ROS interface for GPMP2, [PIPER](https://github.com/gtrll/piper) which is up to date.

**Comment by hclin77923** [comment]
Thank you for the information!

John Hsien-Chung Lin (林顯仲), Ph.D.
Email: hclin@berkeley.edu
Phone: 1(510)693-7610
