### ISSUE TITLE
The XML files of robot about sphere information

### ISSUE THREAD

**Issue by yousiri** [gtrll/gpmp2#26]
Hello Jing Dong and Mustafa Mukadam,

Thank you for sharing the source code, I am very interested in reading articles from you recently.
Now I want to experiment with my robot model, how can I get the XML file like "barrettwam_gpmp2spheres.robot.xml" ? Can I only write it manually?
Really appreciate it! Thank you!

Best Regards,
kai mi

**Comment by mhmukadam** [comment]
Thank you for your interest! In general urdf files are available for most commercial robots. These can be easily converted to the format required by OpenRAVE, however the spheres have to be set up manually within the file for your specific robot.
