### ISSUE TITLE
build the physical body

### ISSUE THREAD

**Issue by Katreenlooper** [gtrll/gpmp2#31]
hi, 
i am trying to build the physical body of my robot model with sphere data.
I know x, y ,z, r are the position and radius of each sphere.
Is there any easy way to build it? when i insert my robot parameter (DH) i don't get good results although i spend many hours to modify the sphere data.
Thanks

**Comment by mhmukadam** [comment]
Currently best way is manually. `CONTRIBUTING` had a todo to build this stuff automatically from robot urdf files, if someone from the community would like to tackle that and submit a PR.
