### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by ishaanmht** [gtrll/gpmp2#33]
I am getting the following Cmake errors. Am I missing something ?
[CMakeError.log](https://github.com/gtrll/gpmp2/files/4232634/CMakeError.log)
[CMakeOutput.log](https://github.com/gtrll/gpmp2/files/4232644/CMakeOutput.log)

**Comment by jimin-liang** [comment]
having the same error, any suggestion?

**Comment by ahuiahui** [comment]
I have the same error......

**Comment by Mr-Xia-6** [comment]
make install
[ 85%] Built target gpmp2
[ 90%] Building CXX object CMakeFiles/gpmp2_matlab_wrapper.dir/wrap/gpmp2/gpmp2_wrapper.cpp.o
In file included from /home/xzq/下载/gpmp2-master/build/wrap/gpmp2/gpmp2_wrapper.cpp:1:0:
/usr/local/include/wrap/matlab.h:32:17: fatal error: mex.h: 没有那个文件或目录
compilation terminated.
CMakeFiles/gpmp2_matlab_wrapper.dir/build.make:71: recipe for target 'CMakeFiles/gpmp2_matlab_wrapper.dir/wrap/gpmp2/gpmp2_wrapper.cpp.o' failed
make[2]: *** [CMakeFiles/gpmp2_matlab_wrapper.dir/wrap/gpmp2/gpmp2_wrapper.cpp.o] Error 1
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/gpmp2_matlab_wrapper.dir/all' failed
make[1]: *** [CMakeFiles/gpmp2_matlab_wrapper.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Mr-Xia-6** [comment]
CMake Error at /usr/local/share/cmake-3.5/Modules/WriteBasicConfigVersionFile.cmake:53 (message):
  No VERSION specified for WRITE_BASIC_CONFIG_VERSION_FILE()
Call Stack (most recent call first):
  /usr/local/share/cmake-3.5/Modules/CMakePackageConfigHelpers.cmake:220 (write_basic_config_version_file)
  /usr/local/lib/cmake/GTSAMCMakeTools/GtsamMakeConfigFile.cmake:34 (write_basic_package_version_file)
  CMakeLists.txt:75 (GtsamMakeConfigFile)


-- Configuring incomplete, errors occurred!
See also "/home/xzq/下载/gpmp2/build/CMakeFiles/CMakeOutput.log".
See also "/home/xzq/下载/gpmp2/build/CMakeFiles/CMakeError.log".

**Comment by ishaanmht** [comment]
I was able to solve this. You can try commenting the line in CMakeLists.txt:75 (GtsamMakeConfigFile). I dont exactly remeber which line I commented. But this worked for me
