### ISSUE TITLE
No VERSION specified for WRITE_BASIC_CONFIG_VERSION_FILE()

### ISSUE THREAD

**Issue by acxz** [gtrll/gpmp2#35]
To reproduce:
1. git clone
2. mkdir build && cd build
3. cmake ..

Error:
```
CMake Error at /usr/share/cmake-3.17/Modules/WriteBasicConfigVersionFile.cmake:43 (message):
  No VERSION specified for WRITE_BASIC_CONFIG_VERSION_FILE()
Call Stack (most recent call first):
  /usr/share/cmake-3.17/Modules/CMakePackageConfigHelpers.cmake:225 (write_basic_config_version_file)
  /usr/lib64/cmake/GTSAMCMakeTools/GtsamMakeConfigFile.cmake:36 (write_basic_package_version_file)
  CMakeLists.txt:75 (GtsamMakeConfigFile)
```

System Info:
CMake: 3.17.1
GTSAM: 4.0.2
GCC: 9.3.0
OS: Arch Linux

**Comment by iskandersauma** [comment]
I had the same problem and managed to solve the problem by using this repository. Maybe you got the same issue. I think it is about having the wrong version of gtsam. 

https://bitbucket.org/gtborg/gtsam/src/develop/

**Comment by acxz** [comment]
It is most likely a GTSAM update is causing this issue. However, I would prefer to use the latest GTSAM version instead of an outdated release. #34  resolved the issue for me though.

**Comment by zhudelong** [comment]
4.0.0-alpha2 branch works well. You may consider using this branch.

**Comment by iskandersauma** [comment]
I managed to make it work with the original repository. Now I got  other issues with orgpmp2....

**Comment by mhmukadam** [comment]
We have found that the current release works stably with gtsam `wrap-expor`t tag. In `CONTRIBUTING` we have left a todo to upgrade the entire library to work with latest version of gtsam, if someone from the community would like to tackle that and send a PR.
