### ISSUE TITLE
building gpmp2 on windows

### ISSUE THREAD

**Issue by rielt12** [gtrll/gpmp2#36]
Hi,
I am trying to compile the matlab toolbox on windows
 I have visual studio 2019 .

When I run cmake .. runs fine.
when I try to build I get linking errors
errors cmake --build .

`
Creating library C:/Users/rielt/Documents/Technion/Spring 2020/ANP/Project/gpmp2/build/lib/Debug/gpmp2Debug.lib an
  d object C:/Users/rielt/Documents/Technion/Spring 2020/ANP/Project/gpmp2/build/lib/Debug/gpmp2Debug.exp

TrajUtils.obj : error LNK2019: unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,c
lass std::allocator<char> > __cdecl gtsam::demangle(char const *)" (?demangle@gtsam@@YA?AV?$basic_string@DU?$char_trait
s@D@std@@V?$allocator@D@2@@std@@PEBD@Z) referenced in function "public: virtual void __cdecl gtsam::GenericValue<class
Eigen::Matrix<double,-1,1,0,-1,1> >::print(class std::basic_string<char,struct std::char_traits<char>,class std::alloca
tor<char> > const &)const " (?print@?$GenericValue@V?$Matrix@N$0?0$00$0A@$0?0$00@Eigen@@@gtsam@@UEBAXAEBV?$basic_string
@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) [C:\Users\rielt\Documents\Technion\Spring 2020\ANP\Project\gpmp2\bui
ld\gpmp2\gpmp2.vcxproj]`

I need to to build because I need the gpmp2_wrapper.mexw64 library for matlab.

**Comment by mhmukadam** [comment]
We have moved to Python wrapper from Matlab.
