### ISSUE TITLE
Change installation instructions

### ISSUE THREAD

**Issue by iskandersauma** [gtrll/gpmp2#37]
The installation instructions states that we should use the command

cmake ..

but when I used the command, it created the gpmp2 core with debug configuration because that is the default configuration. Change the line to

cmake -DCMAKE_BUILD_TYPE=Release ..

To ensure that the right configuration is used

**Comment by mhmukadam** [comment]
These are optional flags and can be used at the discretion of users. We assume users have working knowledge of cmake so adding this to installation instructions doesn't seem necessary.
