### ISSUE TITLE
cmake

### ISSUE THREAD

**Issue by Mr-Xia-6** [gtrll/gpmp2#38]
CMake Error at /usr/local/share/cmake-3.5/Modules/WriteBasicConfigVersionFile.cmake:53 (message):
No VERSION specified for WRITE_BASIC_CONFIG_VERSION_FILE()
Call Stack (most recent call first):
/usr/local/share/cmake-3.5/Modules/CMakePackageConfigHelpers.cmake:220 (write_basic_config_version_file)
/usr/local/lib/cmake/GTSAMCMakeTools/GtsamMakeConfigFile.cmake:34 (write_basic_package_version_file)
CMakeLists.txt:75 (GtsamMakeConfigFile)

-- Configuring incomplete, errors occurred!
See also "/home/xzq/下载/gpmp2/build/CMakeFiles/CMakeOutput.log".
See also "/home/xzq/下载/gpmp2/build/CMakeFiles/CMakeError.log".

**Comment by udtrobo** [comment]
I am facing the same issue. I guess the new version of cmake and other dependencies don't support anymore.  I am requesting authors to provide some guidance here.

**Comment by barbosafs** [comment]
Take a look at #34, it should fix this problem.
