### ISSUE TITLE
matlab未定义函数或变量point2

### ISSUE THREAD

**Issue by Mr-Xia-6** [gtrll/gpmp2#39]
matlab未定义函数或变量point2

**Comment by barbosafs** [comment]
I had the same issue recently, but the solution is simple.
This error just means that MATLAB wasn't able to find the repository. So all you have to do is to make sure that both gtsam and gpmp2 toolboxes are included in the MATLAB path.

**Comment by yangfan3300** [comment]
Have you solved it?I have the same issue.

**Comment by yangfan3300** [comment]
> I had the same issue recently, but the solution is simple.
> This error just means that MATLAB wasn't able to find the repository. So all you have to do is to make sure that both gtsam and gpmp2 toolboxes are included in the MATLAB path.

I add them,but I have the issue too.

**Comment by mhmukadam** [comment]
We have moved to Python wrapper from Matlab.
