### ISSUE TITLE
Bug with params in MobileBase example

### ISSUE THREAD

**Issue by mfinean** [gtrll/gpmp2#48]
The params in the MobileMap1 (used in MobileBaseFactorGraphExample) are set to have an env_size of [500,500] but the resultant map is [999,999] as a result of the add_obstacle function. The easiest solution here is to change the rows and cols in generate2Ddataset to be 1000 then everything works as intended and the dataset contains the correct params.

https://github.com/gtrll/gpmp2/blob/5df0455362b36d9e8c5c2d8991ebf581f466c235/matlab/%2Bgpmp2/generate2Ddataset.m#L62

**Comment by mhmukadam** [comment]
We have moved to Python wrapper from Matlab. If you find this issue there, please feel free to submit a PR.
