### ISSUE TITLE
Changing Source to an IQ File breaks framer.py

### ISSUE THREAD

**Issue by princeje** [gtrll/gpmp2#59]
**USING Gnuradio 3.8***

I'm trying to replay recorded adsb signals and display it using this repo. In order to record adsb signals and use it as as source i'm using repos https://osmocom.org/projects/rtl-sdr/wiki, and https://osmocom.org/projects/rtl-sdr/wiki. **If i change the source in /examples/adsb_rx.py from USRP to RTL-SDR, It works fine when using a usb RTL-SDR dongle and ADSB data is shown correctly.**

If I try to use a recorded adsb.bin IQ file. I get this error trying to run the script:

```
  Time    ICAO  Callsign  Alt  Climb Speed Hdng   Latitude    Longitude  Msgs
                            ft  ft/m    kt   deg         deg         deg     QXcbConnection: XCB error: 170 (Unknown), sequence: 170, resource id: 90, major code: 146 (Unknown), minor code: 20
/usr/lib/python3/dist-packages/adsb/framer.py:84: RuntimeWarning: invalid value encountered in greater_equal
  in0_pulses[np.insert(in0[0:N], 0, self.prev_in0) >= self.threshold] = 1
/usr/lib/python3/dist-packages/adsb/framer.py:145: RuntimeWarning: invalid value encountered in greater
  pulses[amps > in0[pulse_idx]/2] = 1
```

I added `print(amps)` to line 145 in frame.py and it shows this is what amps equals when using a usb RTL-SDR dongle and this is normal:

```
[ 0.09475831  0.06917237  0.03871582  0.0001416   0.00158203  0.05745361
  0.04256104  0.00042236  0.02970704  0.04187744  0.00833252  0.01017578
  0.0504712   0.03235596  0.10462159  0.01111573]
[ 0.04187744  0.00833252  0.01017578  0.0504712   0.03235596  0.10462159
  0.01111573  0.01859863  0.0079541   0.00926025  0.10076416  0.0188916
  0.10296144  0.01682862  0.01204346  0.10485352]
```

When using Device argument: "file='/root/adsb_capture.bin',rate=2e6,freq=1090e6" and run the script amps equals something like:
```
[ inf   0.  inf  nan  inf  nan  inf  inf  inf   0.  inf   0.  inf  inf  inf
  inf]
[ inf  nan  inf  nan  inf  inf  inf   0.  inf   0.  inf  inf  inf  inf   0.
  inf]
```
  
What exactly is going on?
![gnuradio_IQ_error](https://user-images.githubusercontent.com/43219414/154287483-d99e62ec-51cb-4a62-ae1b-91dd2c84dbd6.png)

**Comment by mhmukadam** [comment]
Doesn't belong to this repo.
